Link:
  blog_page: "https://note.com/musume_yokan/"
  facebook: "http://www.facebook.com/share.php?u=http://titechdramaclub.yu-nagi.com/"
  twitter: "http://twitter.com/share?text=%e5%8a%87%e5%9b%a3%e5%a8%98%e3%81%ae%e4%ba%88%e6%84%9f%e5%85%ac%e5%bc%8fHP%2d%e6%9d%b1%e4%ba%ac%e5%b7%a5%e6%a5%ad%e5%a4%a7%e5%ad%a6%e6%bc%94%e5%8a%87%e7%a0%94%e7%a9%b6%e9%83%a8&amp;url=http://titechdramaclub.yu-nagi.com&via=musumenoyokan"
  